version: "3"

tasks:
  generate:
    desc: Clean spec, run Fern code generation, and apply patches
    cmds:
      - python3 tools/specclean/clean_pfsense_spec.py specs/v2.7/openapi.json specs/v2.7/openapi-clean.json
      - cmd: fern generate --local
        dir: fern
      - task: generate:patch

  generate:patch:
    desc: Patch Fern-generated code for known issues
    cmds:
      - |
        # Fix Basic Auth header format - remove space between username and password
        # See: https://github.com/fern-api/fern/issues/6510
        sed -i '' 's/r\.Username+": "+r\.Password/r.Username+":"+r.Password/g' pkg/client/core/request_option.go

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./... {{.CLI_ARGS}}

  test:
    desc: Run tests
    cmds:
      - go test ./... {{.CLI_ARGS}}

  build:
    desc: Build all packages and examples
    cmds:
      - go build ./...
      - go build ./examples/...

  clean:
    desc: Remove generated files
    cmds:
      - rm -rf pkg/client/
      - rm -f specs/v2.7/openapi-clean.json

  check:
    desc: Run lint, test, and build
    cmds:
      - task: lint
      - task: test
      - task: build
