// This file was auto-generated by Fern from our API Definition.

package client

import (
	auth "github.com/danielmichaels/go-pfrest/pkg/client/auth"
	core "github.com/danielmichaels/go-pfrest/pkg/client/core"
	diagnostics "github.com/danielmichaels/go-pfrest/pkg/client/diagnostics"
	firewall "github.com/danielmichaels/go-pfrest/pkg/client/firewall"
	graphql "github.com/danielmichaels/go-pfrest/pkg/client/graphql"
	interface_ "github.com/danielmichaels/go-pfrest/pkg/client/interface_"
	option "github.com/danielmichaels/go-pfrest/pkg/client/option"
	routing "github.com/danielmichaels/go-pfrest/pkg/client/routing"
	services "github.com/danielmichaels/go-pfrest/pkg/client/services"
	status "github.com/danielmichaels/go-pfrest/pkg/client/status"
	system "github.com/danielmichaels/go-pfrest/pkg/client/system"
	user "github.com/danielmichaels/go-pfrest/pkg/client/user"
	vpn "github.com/danielmichaels/go-pfrest/pkg/client/vpn"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	Auth        *auth.Client
	Diagnostics *diagnostics.Client
	Firewall    *firewall.Client
	Graphql     *graphql.Client
	Interface   *interface_.Client
	Routing     *routing.Client
	Services    *services.Client
	Status      *status.Client
	System      *system.Client
	User        *user.Client
	Vpn         *vpn.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:      options.ToHeader(),
		Auth:        auth.NewClient(opts...),
		Diagnostics: diagnostics.NewClient(opts...),
		Firewall:    firewall.NewClient(opts...),
		Graphql:     graphql.NewClient(opts...),
		Interface:   interface_.NewClient(opts...),
		Routing:     routing.NewClient(opts...),
		Services:    services.NewClient(opts...),
		Status:      status.NewClient(opts...),
		System:      system.NewClient(opts...),
		User:        user.NewClient(opts...),
		Vpn:         vpn.NewClient(opts...),
	}
}
