// This file was auto-generated by Fern from our API Definition.

package graphql

import (
	context "context"
	pkgclient "github.com/danielmichaels/go-pfrest/pkg/client"
	core "github.com/danielmichaels/go-pfrest/pkg/client/core"
	option "github.com/danielmichaels/go-pfrest/pkg/client/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// <h3>Description:</h3>Execute a GraphQL query. For more information on utilizing the GraphQL API, please refer to https://pfrest.org/graphql.<br><h3>Details:</h3>**Endpoint type**: Singular<br>**Associated model**: GraphQL<br>**Parent model**: None<br>**Requires authentication**: Yes<br>**Supported authentication modes:** [ BasicAuth, JWTAuth, KeyAuth ]<br>**Allowed privileges**: [ page-all, api-v2-graphql-post ]<br>**Required packages**: [ None ]<br>**Applies immediately**: Not Applicable<br>**Utilizes cache**: None
func (c *Client) PostGraphQlEndpoint(
	ctx context.Context,
	request *pkgclient.PostGraphQlEndpointRequest,
	opts ...option.RequestOption,
) (*pkgclient.PostGraphQlEndpointResponse, error) {
	options := core.NewRequestOptions(opts...)

	baseURL := ""
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	if options.BaseURL != "" {
		baseURL = options.BaseURL
	}
	endpointURL := baseURL + "/" + "api/v2/graphql"

	headers := core.MergeHeaders(c.header.Clone(), options.ToHeader())

	var response *pkgclient.PostGraphQlEndpointResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:         endpointURL,
			Method:      http.MethodPost,
			MaxAttempts: options.MaxAttempts,
			Headers:     headers,
			Client:      options.HTTPClient,
			Request:     request,
			Response:    &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
