// This file was auto-generated by Fern from our API Definition.

package pfclientapi

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/danielmichaels/go-pfrest/pkg/client/core"
)

type DeleteAuthKeyEndpointRequest struct {
	// The ID of the object to target.
	ID *string `json:"-"`
}

type DeleteAuthKeysEndpointRequest struct {
	// The maximum number of objects to delete at once. Set to 0 for no limit.
	Limit *int `json:"-"`
	// The starting point in the dataset to begin fetching objects.
	Offset *int `json:"-"`
	// The arbitrary query parameters to include in the request.<br><br>Note: This does not define an actual parameter, rather it allows for any arbitrary query parameters to be included in the request.
	Query *string `json:"-"`
}

type GetAuthKeysEndpointRequest struct {
	// The number of objects to obtain at once. Set to 0 for no limit.
	Limit *int `json:"-"`
	// The starting point in the dataset to begin fetching objects.
	Offset *int `json:"-"`
	// The fields to sort response data by.
	SortBy *string `json:"-"`
	// The order to sort response data by.
	SortOrder *GetAuthKeysEndpointRequestSortOrder `json:"-"`
	// The sort flag to use to customize the behavior of the sort.
	SortFlags *GetAuthKeysEndpointRequestSortFlags `json:"-"`
	// The arbitrary query parameters to include in the request.<br><br>Note: This does not define a real parameter (e.g. there is no `query` parameter), rather it allows for any arbitrary query parameters to be included in the request.
	Query *string `json:"-"`
}

type PostAuthJwtEndpointRequest struct {
	// The generated JWT that can be used for JWT authentication.<br>
	Token *string `json:"token,omitempty"`
}

type PostAuthKeyEndpointRequest struct {
	// Sets a description for this API key. This is used to identify the key's purpose and cannot be changed once created.<br>
	Descr *string `json:"descr,omitempty"`
	// The username this API key is issued to.<br>
	Username *string `json:"username,omitempty"`
	// The hash algorithm used for this API key. It is recommended to increase the strength of the algorithm for keys assigned to privileged users.<br>
	HashAlgo *RestapiKeyHashAlgo `json:"hash_algo,omitempty"`
	// The length of the API key (in bytes). Greater key lengths provide greater security, but also increase the number of characters used in the key string.<br>
	LengthBytes *int `json:"length_bytes,omitempty"`
	// The hash of the generated API key<br>
	Hash *string `json:"hash,omitempty"`
	// The real API key. This value is not stored internally and cannot be recovered if lost.<br>
	Key *string `json:"key,omitempty"`
}

type RestapiKey struct {
	// Sets a description for this API key. This is used to identify the key's purpose and cannot be changed once created.<br>
	Descr *string `json:"descr,omitempty"`
	// The username this API key is issued to.<br>
	Username *string `json:"username,omitempty"`
	// The hash algorithm used for this API key. It is recommended to increase the strength of the algorithm for keys assigned to privileged users.<br>
	HashAlgo *RestapiKeyHashAlgo `json:"hash_algo,omitempty"`
	// The length of the API key (in bytes). Greater key lengths provide greater security, but also increase the number of characters used in the key string.<br>
	LengthBytes *int `json:"length_bytes,omitempty"`
	// The hash of the generated API key<br>
	Hash *string `json:"hash,omitempty"`
	// The real API key. This value is not stored internally and cannot be recovered if lost.<br>
	Key *string `json:"key,omitempty"`

	_rawJSON json.RawMessage
}

func (r *RestapiKey) UnmarshalJSON(data []byte) error {
	type unmarshaler RestapiKey
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RestapiKey(value)
	r._rawJSON = json.RawMessage(data)
	return nil
}

func (r *RestapiKey) String() string {
	if len(r._rawJSON) > 0 {
		if value, err := core.StringifyJSON(r._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// The hash algorithm used for this API key. It is recommended to increase the strength of the algorithm for keys assigned to privileged users.<br>
type RestapiKeyHashAlgo string

const (
	RestapiKeyHashAlgoSha256 RestapiKeyHashAlgo = "sha256"
	RestapiKeyHashAlgoSha384 RestapiKeyHashAlgo = "sha384"
	RestapiKeyHashAlgoSha512 RestapiKeyHashAlgo = "sha512"
)

func NewRestapiKeyHashAlgoFromString(s string) (RestapiKeyHashAlgo, error) {
	switch s {
	case "sha256":
		return RestapiKeyHashAlgoSha256, nil
	case "sha384":
		return RestapiKeyHashAlgoSha384, nil
	case "sha512":
		return RestapiKeyHashAlgoSha512, nil
	}
	var t RestapiKeyHashAlgo
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RestapiKeyHashAlgo) Ptr() *RestapiKeyHashAlgo {
	return &r
}

type Restapijwt struct {
	// The generated JWT that can be used for JWT authentication.<br>
	Token *string `json:"token,omitempty"`

	_rawJSON json.RawMessage
}

func (r *Restapijwt) UnmarshalJSON(data []byte) error {
	type unmarshaler Restapijwt
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = Restapijwt(value)
	r._rawJSON = json.RawMessage(data)
	return nil
}

func (r *Restapijwt) String() string {
	if len(r._rawJSON) > 0 {
		if value, err := core.StringifyJSON(r._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type DeleteAuthKeyEndpointRequestID struct {
	typeName string
	Integer  int
	String   string
}

func NewDeleteAuthKeyEndpointRequestIDFromInteger(value int) *DeleteAuthKeyEndpointRequestID {
	return &DeleteAuthKeyEndpointRequestID{typeName: "integer", Integer: value}
}

func NewDeleteAuthKeyEndpointRequestIDFromString(value string) *DeleteAuthKeyEndpointRequestID {
	return &DeleteAuthKeyEndpointRequestID{typeName: "string", String: value}
}

func (d *DeleteAuthKeyEndpointRequestID) UnmarshalJSON(data []byte) error {
	var valueInteger int
	if err := json.Unmarshal(data, &valueInteger); err == nil {
		d.typeName = "integer"
		d.Integer = valueInteger
		return nil
	}
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		d.typeName = "string"
		d.String = valueString
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, d)
}

func (d DeleteAuthKeyEndpointRequestID) MarshalJSON() ([]byte, error) {
	switch d.typeName {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", d.typeName, d)
	case "integer":
		return json.Marshal(d.Integer)
	case "string":
		return json.Marshal(d.String)
	}
}

type DeleteAuthKeyEndpointRequestIDVisitor interface {
	VisitInteger(int) error
	VisitString(string) error
}

func (d *DeleteAuthKeyEndpointRequestID) Accept(visitor DeleteAuthKeyEndpointRequestIDVisitor) error {
	switch d.typeName {
	default:
		return fmt.Errorf("invalid type %s in %T", d.typeName, d)
	case "integer":
		return visitor.VisitInteger(d.Integer)
	case "string":
		return visitor.VisitString(d.String)
	}
}

type DeleteAuthKeyEndpointResponse struct {
	Data *DeleteAuthKeyEndpointResponseData `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (d *DeleteAuthKeyEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteAuthKeyEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteAuthKeyEndpointResponse(value)
	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteAuthKeyEndpointResponse) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeleteAuthKeyEndpointResponseData struct {
	// Sets a description for this API key. This is used to identify the key's purpose and cannot be changed once created.<br>
	Descr *string `json:"descr,omitempty"`
	// The username this API key is issued to.<br>
	Username *string `json:"username,omitempty"`
	// The hash algorithm used for this API key. It is recommended to increase the strength of the algorithm for keys assigned to privileged users.<br>
	HashAlgo *RestapiKeyHashAlgo `json:"hash_algo,omitempty"`
	// The length of the API key (in bytes). Greater key lengths provide greater security, but also increase the number of characters used in the key string.<br>
	LengthBytes *int `json:"length_bytes,omitempty"`
	// The hash of the generated API key<br>
	Hash *string `json:"hash,omitempty"`
	// The real API key. This value is not stored internally and cannot be recovered if lost.<br>
	Key *string `json:"key,omitempty"`
	ID  *int    `json:"id,omitempty"`

	_rawJSON json.RawMessage
}

func (d *DeleteAuthKeyEndpointResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteAuthKeyEndpointResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteAuthKeyEndpointResponseData(value)
	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteAuthKeyEndpointResponseData) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeleteAuthKeysEndpointResponse struct {
	Data []*DeleteAuthKeysEndpointResponseDataItem `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (d *DeleteAuthKeysEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteAuthKeysEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteAuthKeysEndpointResponse(value)
	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteAuthKeysEndpointResponse) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeleteAuthKeysEndpointResponseDataItem struct {
	// Sets a description for this API key. This is used to identify the key's purpose and cannot be changed once created.<br>
	Descr *string `json:"descr,omitempty"`
	// The username this API key is issued to.<br>
	Username *string `json:"username,omitempty"`
	// The hash algorithm used for this API key. It is recommended to increase the strength of the algorithm for keys assigned to privileged users.<br>
	HashAlgo *RestapiKeyHashAlgo `json:"hash_algo,omitempty"`
	// The length of the API key (in bytes). Greater key lengths provide greater security, but also increase the number of characters used in the key string.<br>
	LengthBytes *int `json:"length_bytes,omitempty"`
	// The hash of the generated API key<br>
	Hash *string `json:"hash,omitempty"`
	// The real API key. This value is not stored internally and cannot be recovered if lost.<br>
	Key *string `json:"key,omitempty"`
	ID  *int    `json:"id,omitempty"`

	_rawJSON json.RawMessage
}

func (d *DeleteAuthKeysEndpointResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteAuthKeysEndpointResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteAuthKeysEndpointResponseDataItem(value)
	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteAuthKeysEndpointResponseDataItem) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type GetAuthKeysEndpointRequestSortFlags string

const (
	GetAuthKeysEndpointRequestSortFlagsSortRegular      GetAuthKeysEndpointRequestSortFlags = "SORT_REGULAR"
	GetAuthKeysEndpointRequestSortFlagsSortNumeric      GetAuthKeysEndpointRequestSortFlags = "SORT_NUMERIC"
	GetAuthKeysEndpointRequestSortFlagsSortString       GetAuthKeysEndpointRequestSortFlags = "SORT_STRING"
	GetAuthKeysEndpointRequestSortFlagsSortLocaleString GetAuthKeysEndpointRequestSortFlags = "SORT_LOCALE_STRING"
	GetAuthKeysEndpointRequestSortFlagsSortNatural      GetAuthKeysEndpointRequestSortFlags = "SORT_NATURAL"
	GetAuthKeysEndpointRequestSortFlagsSortFlagCase     GetAuthKeysEndpointRequestSortFlags = "SORT_FLAG_CASE"
)

func NewGetAuthKeysEndpointRequestSortFlagsFromString(s string) (GetAuthKeysEndpointRequestSortFlags, error) {
	switch s {
	case "SORT_REGULAR":
		return GetAuthKeysEndpointRequestSortFlagsSortRegular, nil
	case "SORT_NUMERIC":
		return GetAuthKeysEndpointRequestSortFlagsSortNumeric, nil
	case "SORT_STRING":
		return GetAuthKeysEndpointRequestSortFlagsSortString, nil
	case "SORT_LOCALE_STRING":
		return GetAuthKeysEndpointRequestSortFlagsSortLocaleString, nil
	case "SORT_NATURAL":
		return GetAuthKeysEndpointRequestSortFlagsSortNatural, nil
	case "SORT_FLAG_CASE":
		return GetAuthKeysEndpointRequestSortFlagsSortFlagCase, nil
	}
	var t GetAuthKeysEndpointRequestSortFlags
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetAuthKeysEndpointRequestSortFlags) Ptr() *GetAuthKeysEndpointRequestSortFlags {
	return &g
}

type GetAuthKeysEndpointRequestSortOrder string

const (
	GetAuthKeysEndpointRequestSortOrderSortAsc  GetAuthKeysEndpointRequestSortOrder = "SORT_ASC"
	GetAuthKeysEndpointRequestSortOrderSortDesc GetAuthKeysEndpointRequestSortOrder = "SORT_DESC"
)

func NewGetAuthKeysEndpointRequestSortOrderFromString(s string) (GetAuthKeysEndpointRequestSortOrder, error) {
	switch s {
	case "SORT_ASC":
		return GetAuthKeysEndpointRequestSortOrderSortAsc, nil
	case "SORT_DESC":
		return GetAuthKeysEndpointRequestSortOrderSortDesc, nil
	}
	var t GetAuthKeysEndpointRequestSortOrder
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetAuthKeysEndpointRequestSortOrder) Ptr() *GetAuthKeysEndpointRequestSortOrder {
	return &g
}

type GetAuthKeysEndpointResponse struct {
	Data []*GetAuthKeysEndpointResponseDataItem `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetAuthKeysEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetAuthKeysEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetAuthKeysEndpointResponse(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetAuthKeysEndpointResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetAuthKeysEndpointResponseDataItem struct {
	// Sets a description for this API key. This is used to identify the key's purpose and cannot be changed once created.<br>
	Descr *string `json:"descr,omitempty"`
	// The username this API key is issued to.<br>
	Username *string `json:"username,omitempty"`
	// The hash algorithm used for this API key. It is recommended to increase the strength of the algorithm for keys assigned to privileged users.<br>
	HashAlgo *RestapiKeyHashAlgo `json:"hash_algo,omitempty"`
	// The length of the API key (in bytes). Greater key lengths provide greater security, but also increase the number of characters used in the key string.<br>
	LengthBytes *int `json:"length_bytes,omitempty"`
	// The hash of the generated API key<br>
	Hash *string `json:"hash,omitempty"`
	// The real API key. This value is not stored internally and cannot be recovered if lost.<br>
	Key *string `json:"key,omitempty"`
	ID  *int    `json:"id,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetAuthKeysEndpointResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler GetAuthKeysEndpointResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetAuthKeysEndpointResponseDataItem(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetAuthKeysEndpointResponseDataItem) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type PostAuthJwtEndpointResponse struct {
	Data *Restapijwt `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (p *PostAuthJwtEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PostAuthJwtEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostAuthJwtEndpointResponse(value)
	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostAuthJwtEndpointResponse) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PostAuthKeyEndpointResponse struct {
	Data *PostAuthKeyEndpointResponseData `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (p *PostAuthKeyEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PostAuthKeyEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostAuthKeyEndpointResponse(value)
	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostAuthKeyEndpointResponse) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PostAuthKeyEndpointResponseData struct {
	// Sets a description for this API key. This is used to identify the key's purpose and cannot be changed once created.<br>
	Descr *string `json:"descr,omitempty"`
	// The username this API key is issued to.<br>
	Username *string `json:"username,omitempty"`
	// The hash algorithm used for this API key. It is recommended to increase the strength of the algorithm for keys assigned to privileged users.<br>
	HashAlgo *RestapiKeyHashAlgo `json:"hash_algo,omitempty"`
	// The length of the API key (in bytes). Greater key lengths provide greater security, but also increase the number of characters used in the key string.<br>
	LengthBytes *int `json:"length_bytes,omitempty"`
	// The hash of the generated API key<br>
	Hash *string `json:"hash,omitempty"`
	// The real API key. This value is not stored internally and cannot be recovered if lost.<br>
	Key *string `json:"key,omitempty"`
	ID  *int    `json:"id,omitempty"`

	_rawJSON json.RawMessage
}

func (p *PostAuthKeyEndpointResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler PostAuthKeyEndpointResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostAuthKeyEndpointResponseData(value)
	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostAuthKeyEndpointResponseData) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
