// This file was auto-generated by Fern from our API Definition.

package pfclientapi

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/danielmichaels/go-pfrest/pkg/client/core"
)

type DeleteDiagnosticsArpTableEndpointRequest struct {
	// The maximum number of objects to delete at once. Set to 0 for no limit.
	Limit *int `json:"-"`
	// The starting point in the dataset to begin fetching objects.
	Offset *int `json:"-"`
	// The arbitrary query parameters to include in the request.<br><br>Note: This does not define an actual parameter, rather it allows for any arbitrary query parameters to be included in the request.
	Query *string `json:"-"`
}

type DeleteDiagnosticsArpTableEntryEndpointRequest struct {
	// The ID of the object to target.
	ID *string `json:"-"`
}

type DeleteDiagnosticsConfigHistoryRevisionEndpointRequest struct {
	// The ID of the object to target.
	ID *string `json:"-"`
}

type DeleteDiagnosticsConfigHistoryRevisionsEndpointRequest struct {
	// The maximum number of objects to delete at once. Set to 0 for no limit.
	Limit *int `json:"-"`
	// The starting point in the dataset to begin fetching objects.
	Offset *int `json:"-"`
	// The arbitrary query parameters to include in the request.<br><br>Note: This does not define an actual parameter, rather it allows for any arbitrary query parameters to be included in the request.
	Query *string `json:"-"`
}

type DeleteDiagnosticsTableEndpointRequest struct {
	// The ID of the object to target.
	ID *string `json:"-"`
}

type GetDiagnosticsArpTableEndpointRequest struct {
	// The number of objects to obtain at once. Set to 0 for no limit.
	Limit *int `json:"-"`
	// The starting point in the dataset to begin fetching objects.
	Offset *int `json:"-"`
	// The fields to sort response data by.
	SortBy *string `json:"-"`
	// The order to sort response data by.
	SortOrder *GetDiagnosticsArpTableEndpointRequestSortOrder `json:"-"`
	// The sort flag to use to customize the behavior of the sort.
	SortFlags *GetDiagnosticsArpTableEndpointRequestSortFlags `json:"-"`
	// The arbitrary query parameters to include in the request.<br><br>Note: This does not define a real parameter (e.g. there is no `query` parameter), rather it allows for any arbitrary query parameters to be included in the request.
	Query *string `json:"-"`
}

type GetDiagnosticsArpTableEntryEndpointRequest struct {
	// The ID of the object to target.
	ID *string `json:"-"`
}

type GetDiagnosticsConfigHistoryRevisionEndpointRequest struct {
	// The ID of the object to target.
	ID *string `json:"-"`
}

type GetDiagnosticsConfigHistoryRevisionsEndpointRequest struct {
	// The number of objects to obtain at once. Set to 0 for no limit.
	Limit *int `json:"-"`
	// The starting point in the dataset to begin fetching objects.
	Offset *int `json:"-"`
	// The fields to sort response data by.
	SortBy *string `json:"-"`
	// The order to sort response data by.
	SortOrder *GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortOrder `json:"-"`
	// The sort flag to use to customize the behavior of the sort.
	SortFlags *GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlags `json:"-"`
	// The arbitrary query parameters to include in the request.<br><br>Note: This does not define a real parameter (e.g. there is no `query` parameter), rather it allows for any arbitrary query parameters to be included in the request.
	Query *string `json:"-"`
}

type GetDiagnosticsTableEndpointRequest struct {
	// The ID of the object to target.
	ID *string `json:"-"`
}

type GetDiagnosticsTablesEndpointRequest struct {
	// The number of objects to obtain at once. Set to 0 for no limit.
	Limit *int `json:"-"`
	// The starting point in the dataset to begin fetching objects.
	Offset *int `json:"-"`
	// The fields to sort response data by.
	SortBy *string `json:"-"`
	// The order to sort response data by.
	SortOrder *GetDiagnosticsTablesEndpointRequestSortOrder `json:"-"`
	// The sort flag to use to customize the behavior of the sort.
	SortFlags *GetDiagnosticsTablesEndpointRequestSortFlags `json:"-"`
	// The arbitrary query parameters to include in the request.<br><br>Note: This does not define a real parameter (e.g. there is no `query` parameter), rather it allows for any arbitrary query parameters to be included in the request.
	Query *string `json:"-"`
}

type PostDiagnosticsCommandPromptEndpointRequest struct {
	// The command to be executed.<br>
	Command *string `json:"command,omitempty"`
	// The output of the executed command.<br>
	Output *string `json:"output,omitempty"`
	// The result code of the executed command.<br>
	ResultCode *int `json:"result_code,omitempty"`
}

type PostDiagnosticsHaltSystemEndpointRequest struct {
	// Run through the call but don't actually initiate a shutdown.<br>
	DryRun *bool `json:"dry_run,omitempty"`
}

type PostDiagnosticsPingEndpointRequest struct {
	// The IP address or hostname to ping.<br>
	Host *string `json:"host,omitempty"`
	// The number of ping requests to send.<br>
	Count *int `json:"count,omitempty"`
	// The source IP address to use for ping requests.<br>
	SourceAddress *string `json:"source_address,omitempty"`
	// The output from the ping command.<br>
	Output *string `json:"output,omitempty"`
	// The result code from the ping command. 0 indicates success.<br>
	ResultCode *int `json:"result_code,omitempty"`
}

type PostDiagnosticsRebootEndpointRequest struct {
	// Run through the call but don't actually initiate a reboot.<br>
	DryRun *bool `json:"dry_run,omitempty"`
}

type ArpTable struct {
	// The hostname associated with the ARP entry.<br>
	Hostname *string `json:"hostname,omitempty"`
	// The IP address associated with the ARP entry.<br>
	IPAddress *string `json:"ip_address,omitempty"`
	// The MAC address associated with the ARP entry.<br>
	MacAddress *string `json:"mac_address,omitempty"`
	// The interface where the ARP entry was registered.<br>
	Interface *string `json:"interface,omitempty"`
	// The type of connection this host utilizes.<br>
	Type *string `json:"type,omitempty"`
	// Indicates whether the ARP entry is permanent in the ARP table.<br>
	Permanent *bool `json:"permanent,omitempty"`
	// The full DNS name associated with this ARP entry.<br>
	Dnsresolve *string `json:"dnsresolve,omitempty"`
	// The expiration time for this ARP entry.<br>
	Expires *string `json:"expires,omitempty"`

	_rawJSON json.RawMessage
}

func (a *ArpTable) UnmarshalJSON(data []byte) error {
	type unmarshaler ArpTable
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = ArpTable(value)
	a._rawJSON = json.RawMessage(data)
	return nil
}

func (a *ArpTable) String() string {
	if len(a._rawJSON) > 0 {
		if value, err := core.StringifyJSON(a._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type CommandPrompt struct {
	// The command to be executed.<br>
	Command *string `json:"command,omitempty"`
	// The output of the executed command.<br>
	Output *string `json:"output,omitempty"`
	// The result code of the executed command.<br>
	ResultCode *int `json:"result_code,omitempty"`

	_rawJSON json.RawMessage
}

func (c *CommandPrompt) UnmarshalJSON(data []byte) error {
	type unmarshaler CommandPrompt
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CommandPrompt(value)
	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CommandPrompt) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ConfigHistoryRevision struct {
	// The time the configuration change was made.<br>
	Time *int `json:"time,omitempty"`
	// The description of the configuration change.<br>
	Description *string `json:"description,omitempty"`
	// The configuration version associated with this change.<br>
	Version *string `json:"version,omitempty"`
	// The file size (in bytes) of the configuration file associated with this change.<br>
	Filesize *int `json:"filesize,omitempty"`

	_rawJSON json.RawMessage
}

func (c *ConfigHistoryRevision) UnmarshalJSON(data []byte) error {
	type unmarshaler ConfigHistoryRevision
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConfigHistoryRevision(value)
	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConfigHistoryRevision) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type Ping struct {
	// The IP address or hostname to ping.<br>
	Host *string `json:"host,omitempty"`
	// The number of ping requests to send.<br>
	Count *int `json:"count,omitempty"`
	// The source IP address to use for ping requests.<br>
	SourceAddress *string `json:"source_address,omitempty"`
	// The output from the ping command.<br>
	Output *string `json:"output,omitempty"`
	// The result code from the ping command. 0 indicates success.<br>
	ResultCode *int `json:"result_code,omitempty"`

	_rawJSON json.RawMessage
}

func (p *Ping) UnmarshalJSON(data []byte) error {
	type unmarshaler Ping
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = Ping(value)
	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *Ping) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type SystemHalt struct {
	// Run through the call but don't actually initiate a shutdown.<br>
	DryRun *bool `json:"dry_run,omitempty"`

	_rawJSON json.RawMessage
}

func (s *SystemHalt) UnmarshalJSON(data []byte) error {
	type unmarshaler SystemHalt
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SystemHalt(value)
	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SystemHalt) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SystemReboot struct {
	// Run through the call but don't actually initiate a reboot.<br>
	DryRun *bool `json:"dry_run,omitempty"`

	_rawJSON json.RawMessage
}

func (s *SystemReboot) UnmarshalJSON(data []byte) error {
	type unmarshaler SystemReboot
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SystemReboot(value)
	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *SystemReboot) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type Table struct {
	// The entries currently in the table.<br>
	Entries []string `json:"entries,omitempty"`

	_rawJSON json.RawMessage
}

func (t *Table) UnmarshalJSON(data []byte) error {
	type unmarshaler Table
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = Table(value)
	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *Table) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type DeleteDiagnosticsArpTableEndpointResponse struct {
	Data []*DeleteDiagnosticsArpTableEndpointResponseDataItem `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (d *DeleteDiagnosticsArpTableEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteDiagnosticsArpTableEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteDiagnosticsArpTableEndpointResponse(value)
	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteDiagnosticsArpTableEndpointResponse) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeleteDiagnosticsArpTableEndpointResponseDataItem struct {
	// The hostname associated with the ARP entry.<br>
	Hostname *string `json:"hostname,omitempty"`
	// The IP address associated with the ARP entry.<br>
	IPAddress *string `json:"ip_address,omitempty"`
	// The MAC address associated with the ARP entry.<br>
	MacAddress *string `json:"mac_address,omitempty"`
	// The interface where the ARP entry was registered.<br>
	Interface *string `json:"interface,omitempty"`
	// The type of connection this host utilizes.<br>
	Type *string `json:"type,omitempty"`
	// Indicates whether the ARP entry is permanent in the ARP table.<br>
	Permanent *bool `json:"permanent,omitempty"`
	// The full DNS name associated with this ARP entry.<br>
	Dnsresolve *string `json:"dnsresolve,omitempty"`
	// The expiration time for this ARP entry.<br>
	Expires *string `json:"expires,omitempty"`
	ID      *int    `json:"id,omitempty"`

	_rawJSON json.RawMessage
}

func (d *DeleteDiagnosticsArpTableEndpointResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteDiagnosticsArpTableEndpointResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteDiagnosticsArpTableEndpointResponseDataItem(value)
	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteDiagnosticsArpTableEndpointResponseDataItem) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeleteDiagnosticsArpTableEntryEndpointRequestID struct {
	typeName string
	Integer  int
	String   string
}

func NewDeleteDiagnosticsArpTableEntryEndpointRequestIDFromInteger(value int) *DeleteDiagnosticsArpTableEntryEndpointRequestID {
	return &DeleteDiagnosticsArpTableEntryEndpointRequestID{typeName: "integer", Integer: value}
}

func NewDeleteDiagnosticsArpTableEntryEndpointRequestIDFromString(value string) *DeleteDiagnosticsArpTableEntryEndpointRequestID {
	return &DeleteDiagnosticsArpTableEntryEndpointRequestID{typeName: "string", String: value}
}

func (d *DeleteDiagnosticsArpTableEntryEndpointRequestID) UnmarshalJSON(data []byte) error {
	var valueInteger int
	if err := json.Unmarshal(data, &valueInteger); err == nil {
		d.typeName = "integer"
		d.Integer = valueInteger
		return nil
	}
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		d.typeName = "string"
		d.String = valueString
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, d)
}

func (d DeleteDiagnosticsArpTableEntryEndpointRequestID) MarshalJSON() ([]byte, error) {
	switch d.typeName {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", d.typeName, d)
	case "integer":
		return json.Marshal(d.Integer)
	case "string":
		return json.Marshal(d.String)
	}
}

type DeleteDiagnosticsArpTableEntryEndpointRequestIDVisitor interface {
	VisitInteger(int) error
	VisitString(string) error
}

func (d *DeleteDiagnosticsArpTableEntryEndpointRequestID) Accept(visitor DeleteDiagnosticsArpTableEntryEndpointRequestIDVisitor) error {
	switch d.typeName {
	default:
		return fmt.Errorf("invalid type %s in %T", d.typeName, d)
	case "integer":
		return visitor.VisitInteger(d.Integer)
	case "string":
		return visitor.VisitString(d.String)
	}
}

type DeleteDiagnosticsArpTableEntryEndpointResponse struct {
	Data *DeleteDiagnosticsArpTableEntryEndpointResponseData `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (d *DeleteDiagnosticsArpTableEntryEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteDiagnosticsArpTableEntryEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteDiagnosticsArpTableEntryEndpointResponse(value)
	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteDiagnosticsArpTableEntryEndpointResponse) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeleteDiagnosticsArpTableEntryEndpointResponseData struct {
	// The hostname associated with the ARP entry.<br>
	Hostname *string `json:"hostname,omitempty"`
	// The IP address associated with the ARP entry.<br>
	IPAddress *string `json:"ip_address,omitempty"`
	// The MAC address associated with the ARP entry.<br>
	MacAddress *string `json:"mac_address,omitempty"`
	// The interface where the ARP entry was registered.<br>
	Interface *string `json:"interface,omitempty"`
	// The type of connection this host utilizes.<br>
	Type *string `json:"type,omitempty"`
	// Indicates whether the ARP entry is permanent in the ARP table.<br>
	Permanent *bool `json:"permanent,omitempty"`
	// The full DNS name associated with this ARP entry.<br>
	Dnsresolve *string `json:"dnsresolve,omitempty"`
	// The expiration time for this ARP entry.<br>
	Expires *string `json:"expires,omitempty"`
	ID      *int    `json:"id,omitempty"`

	_rawJSON json.RawMessage
}

func (d *DeleteDiagnosticsArpTableEntryEndpointResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteDiagnosticsArpTableEntryEndpointResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteDiagnosticsArpTableEntryEndpointResponseData(value)
	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteDiagnosticsArpTableEntryEndpointResponseData) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeleteDiagnosticsConfigHistoryRevisionEndpointRequestID struct {
	typeName string
	Integer  int
	String   string
}

func NewDeleteDiagnosticsConfigHistoryRevisionEndpointRequestIDFromInteger(value int) *DeleteDiagnosticsConfigHistoryRevisionEndpointRequestID {
	return &DeleteDiagnosticsConfigHistoryRevisionEndpointRequestID{typeName: "integer", Integer: value}
}

func NewDeleteDiagnosticsConfigHistoryRevisionEndpointRequestIDFromString(value string) *DeleteDiagnosticsConfigHistoryRevisionEndpointRequestID {
	return &DeleteDiagnosticsConfigHistoryRevisionEndpointRequestID{typeName: "string", String: value}
}

func (d *DeleteDiagnosticsConfigHistoryRevisionEndpointRequestID) UnmarshalJSON(data []byte) error {
	var valueInteger int
	if err := json.Unmarshal(data, &valueInteger); err == nil {
		d.typeName = "integer"
		d.Integer = valueInteger
		return nil
	}
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		d.typeName = "string"
		d.String = valueString
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, d)
}

func (d DeleteDiagnosticsConfigHistoryRevisionEndpointRequestID) MarshalJSON() ([]byte, error) {
	switch d.typeName {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", d.typeName, d)
	case "integer":
		return json.Marshal(d.Integer)
	case "string":
		return json.Marshal(d.String)
	}
}

type DeleteDiagnosticsConfigHistoryRevisionEndpointRequestIDVisitor interface {
	VisitInteger(int) error
	VisitString(string) error
}

func (d *DeleteDiagnosticsConfigHistoryRevisionEndpointRequestID) Accept(visitor DeleteDiagnosticsConfigHistoryRevisionEndpointRequestIDVisitor) error {
	switch d.typeName {
	default:
		return fmt.Errorf("invalid type %s in %T", d.typeName, d)
	case "integer":
		return visitor.VisitInteger(d.Integer)
	case "string":
		return visitor.VisitString(d.String)
	}
}

type DeleteDiagnosticsConfigHistoryRevisionEndpointResponse struct {
	Data *DeleteDiagnosticsConfigHistoryRevisionEndpointResponseData `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (d *DeleteDiagnosticsConfigHistoryRevisionEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteDiagnosticsConfigHistoryRevisionEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteDiagnosticsConfigHistoryRevisionEndpointResponse(value)
	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteDiagnosticsConfigHistoryRevisionEndpointResponse) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeleteDiagnosticsConfigHistoryRevisionEndpointResponseData struct {
	// The time the configuration change was made.<br>
	Time *int `json:"time,omitempty"`
	// The description of the configuration change.<br>
	Description *string `json:"description,omitempty"`
	// The configuration version associated with this change.<br>
	Version *string `json:"version,omitempty"`
	// The file size (in bytes) of the configuration file associated with this change.<br>
	Filesize *int `json:"filesize,omitempty"`
	ID       *int `json:"id,omitempty"`

	_rawJSON json.RawMessage
}

func (d *DeleteDiagnosticsConfigHistoryRevisionEndpointResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteDiagnosticsConfigHistoryRevisionEndpointResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteDiagnosticsConfigHistoryRevisionEndpointResponseData(value)
	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteDiagnosticsConfigHistoryRevisionEndpointResponseData) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeleteDiagnosticsConfigHistoryRevisionsEndpointResponse struct {
	Data []*DeleteDiagnosticsConfigHistoryRevisionsEndpointResponseDataItem `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (d *DeleteDiagnosticsConfigHistoryRevisionsEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteDiagnosticsConfigHistoryRevisionsEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteDiagnosticsConfigHistoryRevisionsEndpointResponse(value)
	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteDiagnosticsConfigHistoryRevisionsEndpointResponse) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeleteDiagnosticsConfigHistoryRevisionsEndpointResponseDataItem struct {
	// The time the configuration change was made.<br>
	Time *int `json:"time,omitempty"`
	// The description of the configuration change.<br>
	Description *string `json:"description,omitempty"`
	// The configuration version associated with this change.<br>
	Version *string `json:"version,omitempty"`
	// The file size (in bytes) of the configuration file associated with this change.<br>
	Filesize *int `json:"filesize,omitempty"`
	ID       *int `json:"id,omitempty"`

	_rawJSON json.RawMessage
}

func (d *DeleteDiagnosticsConfigHistoryRevisionsEndpointResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteDiagnosticsConfigHistoryRevisionsEndpointResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteDiagnosticsConfigHistoryRevisionsEndpointResponseDataItem(value)
	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteDiagnosticsConfigHistoryRevisionsEndpointResponseDataItem) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeleteDiagnosticsTableEndpointRequestID struct {
	typeName string
	Integer  int
	String   string
}

func NewDeleteDiagnosticsTableEndpointRequestIDFromInteger(value int) *DeleteDiagnosticsTableEndpointRequestID {
	return &DeleteDiagnosticsTableEndpointRequestID{typeName: "integer", Integer: value}
}

func NewDeleteDiagnosticsTableEndpointRequestIDFromString(value string) *DeleteDiagnosticsTableEndpointRequestID {
	return &DeleteDiagnosticsTableEndpointRequestID{typeName: "string", String: value}
}

func (d *DeleteDiagnosticsTableEndpointRequestID) UnmarshalJSON(data []byte) error {
	var valueInteger int
	if err := json.Unmarshal(data, &valueInteger); err == nil {
		d.typeName = "integer"
		d.Integer = valueInteger
		return nil
	}
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		d.typeName = "string"
		d.String = valueString
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, d)
}

func (d DeleteDiagnosticsTableEndpointRequestID) MarshalJSON() ([]byte, error) {
	switch d.typeName {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", d.typeName, d)
	case "integer":
		return json.Marshal(d.Integer)
	case "string":
		return json.Marshal(d.String)
	}
}

type DeleteDiagnosticsTableEndpointRequestIDVisitor interface {
	VisitInteger(int) error
	VisitString(string) error
}

func (d *DeleteDiagnosticsTableEndpointRequestID) Accept(visitor DeleteDiagnosticsTableEndpointRequestIDVisitor) error {
	switch d.typeName {
	default:
		return fmt.Errorf("invalid type %s in %T", d.typeName, d)
	case "integer":
		return visitor.VisitInteger(d.Integer)
	case "string":
		return visitor.VisitString(d.String)
	}
}

type DeleteDiagnosticsTableEndpointResponse struct {
	Data *DeleteDiagnosticsTableEndpointResponseData `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (d *DeleteDiagnosticsTableEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteDiagnosticsTableEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteDiagnosticsTableEndpointResponse(value)
	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteDiagnosticsTableEndpointResponse) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeleteDiagnosticsTableEndpointResponseData struct {
	// The entries currently in the table.<br>
	Entries []string `json:"entries,omitempty"`
	ID      *string  `json:"id,omitempty"`

	_rawJSON json.RawMessage
}

func (d *DeleteDiagnosticsTableEndpointResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteDiagnosticsTableEndpointResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteDiagnosticsTableEndpointResponseData(value)
	d._rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteDiagnosticsTableEndpointResponseData) String() string {
	if len(d._rawJSON) > 0 {
		if value, err := core.StringifyJSON(d._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type GetDiagnosticsArpTableEndpointRequestSortFlags string

const (
	GetDiagnosticsArpTableEndpointRequestSortFlagsSortRegular      GetDiagnosticsArpTableEndpointRequestSortFlags = "SORT_REGULAR"
	GetDiagnosticsArpTableEndpointRequestSortFlagsSortNumeric      GetDiagnosticsArpTableEndpointRequestSortFlags = "SORT_NUMERIC"
	GetDiagnosticsArpTableEndpointRequestSortFlagsSortString       GetDiagnosticsArpTableEndpointRequestSortFlags = "SORT_STRING"
	GetDiagnosticsArpTableEndpointRequestSortFlagsSortLocaleString GetDiagnosticsArpTableEndpointRequestSortFlags = "SORT_LOCALE_STRING"
	GetDiagnosticsArpTableEndpointRequestSortFlagsSortNatural      GetDiagnosticsArpTableEndpointRequestSortFlags = "SORT_NATURAL"
	GetDiagnosticsArpTableEndpointRequestSortFlagsSortFlagCase     GetDiagnosticsArpTableEndpointRequestSortFlags = "SORT_FLAG_CASE"
)

func NewGetDiagnosticsArpTableEndpointRequestSortFlagsFromString(s string) (GetDiagnosticsArpTableEndpointRequestSortFlags, error) {
	switch s {
	case "SORT_REGULAR":
		return GetDiagnosticsArpTableEndpointRequestSortFlagsSortRegular, nil
	case "SORT_NUMERIC":
		return GetDiagnosticsArpTableEndpointRequestSortFlagsSortNumeric, nil
	case "SORT_STRING":
		return GetDiagnosticsArpTableEndpointRequestSortFlagsSortString, nil
	case "SORT_LOCALE_STRING":
		return GetDiagnosticsArpTableEndpointRequestSortFlagsSortLocaleString, nil
	case "SORT_NATURAL":
		return GetDiagnosticsArpTableEndpointRequestSortFlagsSortNatural, nil
	case "SORT_FLAG_CASE":
		return GetDiagnosticsArpTableEndpointRequestSortFlagsSortFlagCase, nil
	}
	var t GetDiagnosticsArpTableEndpointRequestSortFlags
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetDiagnosticsArpTableEndpointRequestSortFlags) Ptr() *GetDiagnosticsArpTableEndpointRequestSortFlags {
	return &g
}

type GetDiagnosticsArpTableEndpointRequestSortOrder string

const (
	GetDiagnosticsArpTableEndpointRequestSortOrderSortAsc  GetDiagnosticsArpTableEndpointRequestSortOrder = "SORT_ASC"
	GetDiagnosticsArpTableEndpointRequestSortOrderSortDesc GetDiagnosticsArpTableEndpointRequestSortOrder = "SORT_DESC"
)

func NewGetDiagnosticsArpTableEndpointRequestSortOrderFromString(s string) (GetDiagnosticsArpTableEndpointRequestSortOrder, error) {
	switch s {
	case "SORT_ASC":
		return GetDiagnosticsArpTableEndpointRequestSortOrderSortAsc, nil
	case "SORT_DESC":
		return GetDiagnosticsArpTableEndpointRequestSortOrderSortDesc, nil
	}
	var t GetDiagnosticsArpTableEndpointRequestSortOrder
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetDiagnosticsArpTableEndpointRequestSortOrder) Ptr() *GetDiagnosticsArpTableEndpointRequestSortOrder {
	return &g
}

type GetDiagnosticsArpTableEndpointResponse struct {
	Data []*GetDiagnosticsArpTableEndpointResponseDataItem `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetDiagnosticsArpTableEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDiagnosticsArpTableEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDiagnosticsArpTableEndpointResponse(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDiagnosticsArpTableEndpointResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetDiagnosticsArpTableEndpointResponseDataItem struct {
	// The hostname associated with the ARP entry.<br>
	Hostname *string `json:"hostname,omitempty"`
	// The IP address associated with the ARP entry.<br>
	IPAddress *string `json:"ip_address,omitempty"`
	// The MAC address associated with the ARP entry.<br>
	MacAddress *string `json:"mac_address,omitempty"`
	// The interface where the ARP entry was registered.<br>
	Interface *string `json:"interface,omitempty"`
	// The type of connection this host utilizes.<br>
	Type *string `json:"type,omitempty"`
	// Indicates whether the ARP entry is permanent in the ARP table.<br>
	Permanent *bool `json:"permanent,omitempty"`
	// The full DNS name associated with this ARP entry.<br>
	Dnsresolve *string `json:"dnsresolve,omitempty"`
	// The expiration time for this ARP entry.<br>
	Expires *string `json:"expires,omitempty"`
	ID      *int    `json:"id,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetDiagnosticsArpTableEndpointResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDiagnosticsArpTableEndpointResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDiagnosticsArpTableEndpointResponseDataItem(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDiagnosticsArpTableEndpointResponseDataItem) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetDiagnosticsArpTableEntryEndpointRequestID struct {
	typeName string
	Integer  int
	String   string
}

func NewGetDiagnosticsArpTableEntryEndpointRequestIDFromInteger(value int) *GetDiagnosticsArpTableEntryEndpointRequestID {
	return &GetDiagnosticsArpTableEntryEndpointRequestID{typeName: "integer", Integer: value}
}

func NewGetDiagnosticsArpTableEntryEndpointRequestIDFromString(value string) *GetDiagnosticsArpTableEntryEndpointRequestID {
	return &GetDiagnosticsArpTableEntryEndpointRequestID{typeName: "string", String: value}
}

func (g *GetDiagnosticsArpTableEntryEndpointRequestID) UnmarshalJSON(data []byte) error {
	var valueInteger int
	if err := json.Unmarshal(data, &valueInteger); err == nil {
		g.typeName = "integer"
		g.Integer = valueInteger
		return nil
	}
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		g.typeName = "string"
		g.String = valueString
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, g)
}

func (g GetDiagnosticsArpTableEntryEndpointRequestID) MarshalJSON() ([]byte, error) {
	switch g.typeName {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", g.typeName, g)
	case "integer":
		return json.Marshal(g.Integer)
	case "string":
		return json.Marshal(g.String)
	}
}

type GetDiagnosticsArpTableEntryEndpointRequestIDVisitor interface {
	VisitInteger(int) error
	VisitString(string) error
}

func (g *GetDiagnosticsArpTableEntryEndpointRequestID) Accept(visitor GetDiagnosticsArpTableEntryEndpointRequestIDVisitor) error {
	switch g.typeName {
	default:
		return fmt.Errorf("invalid type %s in %T", g.typeName, g)
	case "integer":
		return visitor.VisitInteger(g.Integer)
	case "string":
		return visitor.VisitString(g.String)
	}
}

type GetDiagnosticsArpTableEntryEndpointResponse struct {
	Data *GetDiagnosticsArpTableEntryEndpointResponseData `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetDiagnosticsArpTableEntryEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDiagnosticsArpTableEntryEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDiagnosticsArpTableEntryEndpointResponse(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDiagnosticsArpTableEntryEndpointResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetDiagnosticsArpTableEntryEndpointResponseData struct {
	// The hostname associated with the ARP entry.<br>
	Hostname *string `json:"hostname,omitempty"`
	// The IP address associated with the ARP entry.<br>
	IPAddress *string `json:"ip_address,omitempty"`
	// The MAC address associated with the ARP entry.<br>
	MacAddress *string `json:"mac_address,omitempty"`
	// The interface where the ARP entry was registered.<br>
	Interface *string `json:"interface,omitempty"`
	// The type of connection this host utilizes.<br>
	Type *string `json:"type,omitempty"`
	// Indicates whether the ARP entry is permanent in the ARP table.<br>
	Permanent *bool `json:"permanent,omitempty"`
	// The full DNS name associated with this ARP entry.<br>
	Dnsresolve *string `json:"dnsresolve,omitempty"`
	// The expiration time for this ARP entry.<br>
	Expires *string `json:"expires,omitempty"`
	ID      *int    `json:"id,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetDiagnosticsArpTableEntryEndpointResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDiagnosticsArpTableEntryEndpointResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDiagnosticsArpTableEntryEndpointResponseData(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDiagnosticsArpTableEntryEndpointResponseData) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetDiagnosticsConfigHistoryRevisionEndpointRequestID struct {
	typeName string
	Integer  int
	String   string
}

func NewGetDiagnosticsConfigHistoryRevisionEndpointRequestIDFromInteger(value int) *GetDiagnosticsConfigHistoryRevisionEndpointRequestID {
	return &GetDiagnosticsConfigHistoryRevisionEndpointRequestID{typeName: "integer", Integer: value}
}

func NewGetDiagnosticsConfigHistoryRevisionEndpointRequestIDFromString(value string) *GetDiagnosticsConfigHistoryRevisionEndpointRequestID {
	return &GetDiagnosticsConfigHistoryRevisionEndpointRequestID{typeName: "string", String: value}
}

func (g *GetDiagnosticsConfigHistoryRevisionEndpointRequestID) UnmarshalJSON(data []byte) error {
	var valueInteger int
	if err := json.Unmarshal(data, &valueInteger); err == nil {
		g.typeName = "integer"
		g.Integer = valueInteger
		return nil
	}
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		g.typeName = "string"
		g.String = valueString
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, g)
}

func (g GetDiagnosticsConfigHistoryRevisionEndpointRequestID) MarshalJSON() ([]byte, error) {
	switch g.typeName {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", g.typeName, g)
	case "integer":
		return json.Marshal(g.Integer)
	case "string":
		return json.Marshal(g.String)
	}
}

type GetDiagnosticsConfigHistoryRevisionEndpointRequestIDVisitor interface {
	VisitInteger(int) error
	VisitString(string) error
}

func (g *GetDiagnosticsConfigHistoryRevisionEndpointRequestID) Accept(visitor GetDiagnosticsConfigHistoryRevisionEndpointRequestIDVisitor) error {
	switch g.typeName {
	default:
		return fmt.Errorf("invalid type %s in %T", g.typeName, g)
	case "integer":
		return visitor.VisitInteger(g.Integer)
	case "string":
		return visitor.VisitString(g.String)
	}
}

type GetDiagnosticsConfigHistoryRevisionEndpointResponse struct {
	Data *GetDiagnosticsConfigHistoryRevisionEndpointResponseData `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetDiagnosticsConfigHistoryRevisionEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDiagnosticsConfigHistoryRevisionEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDiagnosticsConfigHistoryRevisionEndpointResponse(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDiagnosticsConfigHistoryRevisionEndpointResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetDiagnosticsConfigHistoryRevisionEndpointResponseData struct {
	// The time the configuration change was made.<br>
	Time *int `json:"time,omitempty"`
	// The description of the configuration change.<br>
	Description *string `json:"description,omitempty"`
	// The configuration version associated with this change.<br>
	Version *string `json:"version,omitempty"`
	// The file size (in bytes) of the configuration file associated with this change.<br>
	Filesize *int `json:"filesize,omitempty"`
	ID       *int `json:"id,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetDiagnosticsConfigHistoryRevisionEndpointResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDiagnosticsConfigHistoryRevisionEndpointResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDiagnosticsConfigHistoryRevisionEndpointResponseData(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDiagnosticsConfigHistoryRevisionEndpointResponseData) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlags string

const (
	GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlagsSortRegular      GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlags = "SORT_REGULAR"
	GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlagsSortNumeric      GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlags = "SORT_NUMERIC"
	GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlagsSortString       GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlags = "SORT_STRING"
	GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlagsSortLocaleString GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlags = "SORT_LOCALE_STRING"
	GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlagsSortNatural      GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlags = "SORT_NATURAL"
	GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlagsSortFlagCase     GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlags = "SORT_FLAG_CASE"
)

func NewGetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlagsFromString(s string) (GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlags, error) {
	switch s {
	case "SORT_REGULAR":
		return GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlagsSortRegular, nil
	case "SORT_NUMERIC":
		return GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlagsSortNumeric, nil
	case "SORT_STRING":
		return GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlagsSortString, nil
	case "SORT_LOCALE_STRING":
		return GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlagsSortLocaleString, nil
	case "SORT_NATURAL":
		return GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlagsSortNatural, nil
	case "SORT_FLAG_CASE":
		return GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlagsSortFlagCase, nil
	}
	var t GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlags
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlags) Ptr() *GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortFlags {
	return &g
}

type GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortOrder string

const (
	GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortOrderSortAsc  GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortOrder = "SORT_ASC"
	GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortOrderSortDesc GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortOrder = "SORT_DESC"
)

func NewGetDiagnosticsConfigHistoryRevisionsEndpointRequestSortOrderFromString(s string) (GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortOrder, error) {
	switch s {
	case "SORT_ASC":
		return GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortOrderSortAsc, nil
	case "SORT_DESC":
		return GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortOrderSortDesc, nil
	}
	var t GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortOrder
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortOrder) Ptr() *GetDiagnosticsConfigHistoryRevisionsEndpointRequestSortOrder {
	return &g
}

type GetDiagnosticsConfigHistoryRevisionsEndpointResponse struct {
	Data []*GetDiagnosticsConfigHistoryRevisionsEndpointResponseDataItem `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetDiagnosticsConfigHistoryRevisionsEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDiagnosticsConfigHistoryRevisionsEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDiagnosticsConfigHistoryRevisionsEndpointResponse(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDiagnosticsConfigHistoryRevisionsEndpointResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetDiagnosticsConfigHistoryRevisionsEndpointResponseDataItem struct {
	// The time the configuration change was made.<br>
	Time *int `json:"time,omitempty"`
	// The description of the configuration change.<br>
	Description *string `json:"description,omitempty"`
	// The configuration version associated with this change.<br>
	Version *string `json:"version,omitempty"`
	// The file size (in bytes) of the configuration file associated with this change.<br>
	Filesize *int `json:"filesize,omitempty"`
	ID       *int `json:"id,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetDiagnosticsConfigHistoryRevisionsEndpointResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDiagnosticsConfigHistoryRevisionsEndpointResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDiagnosticsConfigHistoryRevisionsEndpointResponseDataItem(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDiagnosticsConfigHistoryRevisionsEndpointResponseDataItem) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetDiagnosticsTableEndpointRequestID struct {
	typeName string
	Integer  int
	String   string
}

func NewGetDiagnosticsTableEndpointRequestIDFromInteger(value int) *GetDiagnosticsTableEndpointRequestID {
	return &GetDiagnosticsTableEndpointRequestID{typeName: "integer", Integer: value}
}

func NewGetDiagnosticsTableEndpointRequestIDFromString(value string) *GetDiagnosticsTableEndpointRequestID {
	return &GetDiagnosticsTableEndpointRequestID{typeName: "string", String: value}
}

func (g *GetDiagnosticsTableEndpointRequestID) UnmarshalJSON(data []byte) error {
	var valueInteger int
	if err := json.Unmarshal(data, &valueInteger); err == nil {
		g.typeName = "integer"
		g.Integer = valueInteger
		return nil
	}
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		g.typeName = "string"
		g.String = valueString
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, g)
}

func (g GetDiagnosticsTableEndpointRequestID) MarshalJSON() ([]byte, error) {
	switch g.typeName {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", g.typeName, g)
	case "integer":
		return json.Marshal(g.Integer)
	case "string":
		return json.Marshal(g.String)
	}
}

type GetDiagnosticsTableEndpointRequestIDVisitor interface {
	VisitInteger(int) error
	VisitString(string) error
}

func (g *GetDiagnosticsTableEndpointRequestID) Accept(visitor GetDiagnosticsTableEndpointRequestIDVisitor) error {
	switch g.typeName {
	default:
		return fmt.Errorf("invalid type %s in %T", g.typeName, g)
	case "integer":
		return visitor.VisitInteger(g.Integer)
	case "string":
		return visitor.VisitString(g.String)
	}
}

type GetDiagnosticsTableEndpointResponse struct {
	Data *GetDiagnosticsTableEndpointResponseData `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetDiagnosticsTableEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDiagnosticsTableEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDiagnosticsTableEndpointResponse(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDiagnosticsTableEndpointResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetDiagnosticsTableEndpointResponseData struct {
	// The entries currently in the table.<br>
	Entries []string `json:"entries,omitempty"`
	ID      *string  `json:"id,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetDiagnosticsTableEndpointResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDiagnosticsTableEndpointResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDiagnosticsTableEndpointResponseData(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDiagnosticsTableEndpointResponseData) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetDiagnosticsTablesEndpointRequestSortFlags string

const (
	GetDiagnosticsTablesEndpointRequestSortFlagsSortRegular      GetDiagnosticsTablesEndpointRequestSortFlags = "SORT_REGULAR"
	GetDiagnosticsTablesEndpointRequestSortFlagsSortNumeric      GetDiagnosticsTablesEndpointRequestSortFlags = "SORT_NUMERIC"
	GetDiagnosticsTablesEndpointRequestSortFlagsSortString       GetDiagnosticsTablesEndpointRequestSortFlags = "SORT_STRING"
	GetDiagnosticsTablesEndpointRequestSortFlagsSortLocaleString GetDiagnosticsTablesEndpointRequestSortFlags = "SORT_LOCALE_STRING"
	GetDiagnosticsTablesEndpointRequestSortFlagsSortNatural      GetDiagnosticsTablesEndpointRequestSortFlags = "SORT_NATURAL"
	GetDiagnosticsTablesEndpointRequestSortFlagsSortFlagCase     GetDiagnosticsTablesEndpointRequestSortFlags = "SORT_FLAG_CASE"
)

func NewGetDiagnosticsTablesEndpointRequestSortFlagsFromString(s string) (GetDiagnosticsTablesEndpointRequestSortFlags, error) {
	switch s {
	case "SORT_REGULAR":
		return GetDiagnosticsTablesEndpointRequestSortFlagsSortRegular, nil
	case "SORT_NUMERIC":
		return GetDiagnosticsTablesEndpointRequestSortFlagsSortNumeric, nil
	case "SORT_STRING":
		return GetDiagnosticsTablesEndpointRequestSortFlagsSortString, nil
	case "SORT_LOCALE_STRING":
		return GetDiagnosticsTablesEndpointRequestSortFlagsSortLocaleString, nil
	case "SORT_NATURAL":
		return GetDiagnosticsTablesEndpointRequestSortFlagsSortNatural, nil
	case "SORT_FLAG_CASE":
		return GetDiagnosticsTablesEndpointRequestSortFlagsSortFlagCase, nil
	}
	var t GetDiagnosticsTablesEndpointRequestSortFlags
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetDiagnosticsTablesEndpointRequestSortFlags) Ptr() *GetDiagnosticsTablesEndpointRequestSortFlags {
	return &g
}

type GetDiagnosticsTablesEndpointRequestSortOrder string

const (
	GetDiagnosticsTablesEndpointRequestSortOrderSortAsc  GetDiagnosticsTablesEndpointRequestSortOrder = "SORT_ASC"
	GetDiagnosticsTablesEndpointRequestSortOrderSortDesc GetDiagnosticsTablesEndpointRequestSortOrder = "SORT_DESC"
)

func NewGetDiagnosticsTablesEndpointRequestSortOrderFromString(s string) (GetDiagnosticsTablesEndpointRequestSortOrder, error) {
	switch s {
	case "SORT_ASC":
		return GetDiagnosticsTablesEndpointRequestSortOrderSortAsc, nil
	case "SORT_DESC":
		return GetDiagnosticsTablesEndpointRequestSortOrderSortDesc, nil
	}
	var t GetDiagnosticsTablesEndpointRequestSortOrder
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetDiagnosticsTablesEndpointRequestSortOrder) Ptr() *GetDiagnosticsTablesEndpointRequestSortOrder {
	return &g
}

type GetDiagnosticsTablesEndpointResponse struct {
	Data []*GetDiagnosticsTablesEndpointResponseDataItem `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetDiagnosticsTablesEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDiagnosticsTablesEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDiagnosticsTablesEndpointResponse(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDiagnosticsTablesEndpointResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetDiagnosticsTablesEndpointResponseDataItem struct {
	// The entries currently in the table.<br>
	Entries []string `json:"entries,omitempty"`
	ID      *string  `json:"id,omitempty"`

	_rawJSON json.RawMessage
}

func (g *GetDiagnosticsTablesEndpointResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDiagnosticsTablesEndpointResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDiagnosticsTablesEndpointResponseDataItem(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDiagnosticsTablesEndpointResponseDataItem) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type PostDiagnosticsCommandPromptEndpointResponse struct {
	Data *CommandPrompt `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (p *PostDiagnosticsCommandPromptEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PostDiagnosticsCommandPromptEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostDiagnosticsCommandPromptEndpointResponse(value)
	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostDiagnosticsCommandPromptEndpointResponse) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PostDiagnosticsHaltSystemEndpointResponse struct {
	Data *SystemHalt `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (p *PostDiagnosticsHaltSystemEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PostDiagnosticsHaltSystemEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostDiagnosticsHaltSystemEndpointResponse(value)
	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostDiagnosticsHaltSystemEndpointResponse) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PostDiagnosticsPingEndpointResponse struct {
	Data *Ping `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (p *PostDiagnosticsPingEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PostDiagnosticsPingEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostDiagnosticsPingEndpointResponse(value)
	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostDiagnosticsPingEndpointResponse) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PostDiagnosticsRebootEndpointResponse struct {
	Data *SystemReboot `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (p *PostDiagnosticsRebootEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PostDiagnosticsRebootEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostDiagnosticsRebootEndpointResponse(value)
	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostDiagnosticsRebootEndpointResponse) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
