// This file was auto-generated by Fern from our API Definition.

package pfclientapi

import (
	json "encoding/json"
	core "github.com/danielmichaels/go-pfrest/pkg/client/core"
)

// The client request data has one or more input validation errors.
type BadRequestError struct {
	*core.APIError
	Body interface{}
}

func (b *BadRequestError) UnmarshalJSON(data []byte) error {
	var body interface{}
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.StatusCode = 400
	b.Body = body
	return nil
}

func (b *BadRequestError) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

func (b *BadRequestError) Unwrap() error {
	return b.APIError
}

// The client's request cannot be fulfilled due to one or more conflicts.
type ConflictError struct {
	*core.APIError
	Body interface{}
}

func (c *ConflictError) UnmarshalJSON(data []byte) error {
	var body interface{}
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.StatusCode = 409
	c.Body = body
	return nil
}

func (c *ConflictError) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

func (c *ConflictError) Unwrap() error {
	return c.APIError
}

// The client has requested a resource that requires a dependency which is not installed.
type FailedDependencyError struct {
	*core.APIError
	Body interface{}
}

func (f *FailedDependencyError) UnmarshalJSON(data []byte) error {
	var body interface{}
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	f.StatusCode = 424
	f.Body = body
	return nil
}

func (f *FailedDependencyError) MarshalJSON() ([]byte, error) {
	return json.Marshal(f.Body)
}

func (f *FailedDependencyError) Unwrap() error {
	return f.APIError
}

// The client does not have sufficient privileges to make this API call.
type ForbiddenError struct {
	*core.APIError
	Body interface{}
}

func (f *ForbiddenError) UnmarshalJSON(data []byte) error {
	var body interface{}
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	f.StatusCode = 403
	f.Body = body
	return nil
}

func (f *ForbiddenError) MarshalJSON() ([]byte, error) {
	return json.Marshal(f.Body)
}

func (f *ForbiddenError) Unwrap() error {
	return f.APIError
}

// The server encountered an unexpected error and cannot complete the request.
type InternalServerError struct {
	*core.APIError
	Body interface{}
}

func (i *InternalServerError) UnmarshalJSON(data []byte) error {
	var body interface{}
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	i.StatusCode = 500
	i.Body = body
	return nil
}

func (i *InternalServerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.Body)
}

func (i *InternalServerError) Unwrap() error {
	return i.APIError
}

// The client has requested an HTTP method that is not supported by the current URL.
type MethodNotAllowedError struct {
	*core.APIError
	Body interface{}
}

func (m *MethodNotAllowedError) UnmarshalJSON(data []byte) error {
	var body interface{}
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	m.StatusCode = 405
	m.Body = body
	return nil
}

func (m *MethodNotAllowedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(m.Body)
}

func (m *MethodNotAllowedError) Unwrap() error {
	return m.APIError
}

// The client has requested content in a format that is not supported.
type NotAcceptableError struct {
	*core.APIError
	Body interface{}
}

func (n *NotAcceptableError) UnmarshalJSON(data []byte) error {
	var body interface{}
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.StatusCode = 406
	n.Body = body
	return nil
}

func (n *NotAcceptableError) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

func (n *NotAcceptableError) Unwrap() error {
	return n.APIError
}

// The client has requested a resource that could not be found.
type NotFoundError struct {
	*core.APIError
	Body interface{}
}

func (n *NotFoundError) UnmarshalJSON(data []byte) error {
	var body interface{}
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.StatusCode = 404
	n.Body = body
	return nil
}

func (n *NotFoundError) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

func (n *NotFoundError) Unwrap() error {
	return n.APIError
}

// The requested service is temporarily unavailable.
type ServiceUnavailableError struct {
	*core.APIError
	Body interface{}
}

func (s *ServiceUnavailableError) UnmarshalJSON(data []byte) error {
	var body interface{}
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	s.StatusCode = 503
	s.Body = body
	return nil
}

func (s *ServiceUnavailableError) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.Body)
}

func (s *ServiceUnavailableError) Unwrap() error {
	return s.APIError
}

// The client has failed to authenticate the API call.
type UnauthorizedError struct {
	*core.APIError
	Body interface{}
}

func (u *UnauthorizedError) UnmarshalJSON(data []byte) error {
	var body interface{}
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 401
	u.Body = body
	return nil
}

func (u *UnauthorizedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnauthorizedError) Unwrap() error {
	return u.APIError
}

// The client has requested a resource that requires a dependency or other requirement that was not met.
type UnprocessableEntityError struct {
	*core.APIError
	Body interface{}
}

func (u *UnprocessableEntityError) UnmarshalJSON(data []byte) error {
	var body interface{}
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 422
	u.Body = body
	return nil
}

func (u *UnprocessableEntityError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnprocessableEntityError) Unwrap() error {
	return u.APIError
}

// The client has requested a content-type that is not supported by the server.
type UnsupportedMediaTypeError struct {
	*core.APIError
	Body interface{}
}

func (u *UnsupportedMediaTypeError) UnmarshalJSON(data []byte) error {
	var body interface{}
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 415
	u.Body = body
	return nil
}

func (u *UnsupportedMediaTypeError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnsupportedMediaTypeError) Unwrap() error {
	return u.APIError
}
