// This file was auto-generated by Fern from our API Definition.

package pfclientapi

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/danielmichaels/go-pfrest/pkg/client/core"
)

type PostGraphQlEndpointRequest struct {
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
	Data *SuccessData `json:"data,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`
}

type Success struct {
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
	Data *SuccessData `json:"data,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (s *Success) UnmarshalJSON(data []byte) error {
	type unmarshaler Success
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = Success(value)
	s._rawJSON = json.RawMessage(data)
	return nil
}

func (s *Success) String() string {
	if len(s._rawJSON) > 0 {
		if value, err := core.StringifyJSON(s._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
type SuccessData struct {
	typeName             string
	StringUnknownMapList []map[string]interface{}
	StringUnknownMap     map[string]interface{}
}

func NewSuccessDataFromStringUnknownMapList(value []map[string]interface{}) *SuccessData {
	return &SuccessData{typeName: "stringUnknownMapList", StringUnknownMapList: value}
}

func NewSuccessDataFromStringUnknownMap(value map[string]interface{}) *SuccessData {
	return &SuccessData{typeName: "stringUnknownMap", StringUnknownMap: value}
}

func (s *SuccessData) UnmarshalJSON(data []byte) error {
	var valueStringUnknownMapList []map[string]interface{}
	if err := json.Unmarshal(data, &valueStringUnknownMapList); err == nil {
		s.typeName = "stringUnknownMapList"
		s.StringUnknownMapList = valueStringUnknownMapList
		return nil
	}
	var valueStringUnknownMap map[string]interface{}
	if err := json.Unmarshal(data, &valueStringUnknownMap); err == nil {
		s.typeName = "stringUnknownMap"
		s.StringUnknownMap = valueStringUnknownMap
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, s)
}

func (s SuccessData) MarshalJSON() ([]byte, error) {
	switch s.typeName {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", s.typeName, s)
	case "stringUnknownMapList":
		return json.Marshal(s.StringUnknownMapList)
	case "stringUnknownMap":
		return json.Marshal(s.StringUnknownMap)
	}
}

type SuccessDataVisitor interface {
	VisitStringUnknownMapList([]map[string]interface{}) error
	VisitStringUnknownMap(map[string]interface{}) error
}

func (s *SuccessData) Accept(visitor SuccessDataVisitor) error {
	switch s.typeName {
	default:
		return fmt.Errorf("invalid type %s in %T", s.typeName, s)
	case "stringUnknownMapList":
		return visitor.VisitStringUnknownMapList(s.StringUnknownMapList)
	case "stringUnknownMap":
		return visitor.VisitStringUnknownMap(s.StringUnknownMap)
	}
}

type PostGraphQlEndpointResponse struct {
	Data *PostGraphQlEndpointResponseData `json:"data,omitempty"`
	// The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`
	// The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
	// The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseID *string `json:"response_id,omitempty"`
	// The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`
	// An array of links to resources that are related to this API response.
	Links map[string]interface{} `json:"_links,omitempty"`

	_rawJSON json.RawMessage
}

func (p *PostGraphQlEndpointResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PostGraphQlEndpointResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostGraphQlEndpointResponse(value)
	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostGraphQlEndpointResponse) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PostGraphQlEndpointResponseData struct {
	typeName             string
	StringUnknownMapList []map[string]interface{}
	StringUnknownMap     map[string]interface{}
}

func NewPostGraphQlEndpointResponseDataFromStringUnknownMapList(value []map[string]interface{}) *PostGraphQlEndpointResponseData {
	return &PostGraphQlEndpointResponseData{typeName: "stringUnknownMapList", StringUnknownMapList: value}
}

func NewPostGraphQlEndpointResponseDataFromStringUnknownMap(value map[string]interface{}) *PostGraphQlEndpointResponseData {
	return &PostGraphQlEndpointResponseData{typeName: "stringUnknownMap", StringUnknownMap: value}
}

func (p *PostGraphQlEndpointResponseData) UnmarshalJSON(data []byte) error {
	var valueStringUnknownMapList []map[string]interface{}
	if err := json.Unmarshal(data, &valueStringUnknownMapList); err == nil {
		p.typeName = "stringUnknownMapList"
		p.StringUnknownMapList = valueStringUnknownMapList
		return nil
	}
	var valueStringUnknownMap map[string]interface{}
	if err := json.Unmarshal(data, &valueStringUnknownMap); err == nil {
		p.typeName = "stringUnknownMap"
		p.StringUnknownMap = valueStringUnknownMap
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, p)
}

func (p PostGraphQlEndpointResponseData) MarshalJSON() ([]byte, error) {
	switch p.typeName {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", p.typeName, p)
	case "stringUnknownMapList":
		return json.Marshal(p.StringUnknownMapList)
	case "stringUnknownMap":
		return json.Marshal(p.StringUnknownMap)
	}
}

type PostGraphQlEndpointResponseDataVisitor interface {
	VisitStringUnknownMapList([]map[string]interface{}) error
	VisitStringUnknownMap(map[string]interface{}) error
}

func (p *PostGraphQlEndpointResponseData) Accept(visitor PostGraphQlEndpointResponseDataVisitor) error {
	switch p.typeName {
	default:
		return fmt.Errorf("invalid type %s in %T", p.typeName, p)
	case "stringUnknownMapList":
		return visitor.VisitStringUnknownMapList(p.StringUnknownMapList)
	case "stringUnknownMap":
		return visitor.VisitStringUnknownMap(p.StringUnknownMap)
	}
}
